###
POST http://localhost:3000/provider/1/topic/gear
Content-Type: application/json
Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcm92aWRlcl9pZCI6IjM4MTE1ZTA4LWVhOTUtMTFlYy1hYTVhLTViZGVjN2VmM2I0OCJ9.k6BIqItVjxjYVUT_EXnP-pHkzJu_6R0UXUye22rmHzs 

{
    "message": "some keys"
}

###
POST http://localhost:3000/provider/1/topic/tomatoes
Content-Type: application/xml
Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcm92aWRlcl9pZCI6IjM4MTE1ZTA4LWVhOTUtMTFlYy1hYTVhLTViZGVjN2VmM2I0OCJ9.k6BIqItVjxjYVUT_EXnP-pHkzJu_6R0UXUye22rmHzs 

<message>
some message
</message>

###
POST http://localhost:3000/provider/1/topic/tomatoes
Content-Type: application/x-yaml
Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcm92aWRlcl9pZCI6IjM4MTE1ZTA4LWVhOTUtMTFlYy1hYTVhLTViZGVjN2VmM2I0OCJ9.k6BIqItVjxjYVUT_EXnP-pHkzJu_6R0UXUye22rmHzs 

message:
    "some message"

###
POST http://localhost:3000/provider/1/topic/tomatoes
Content-Type: text/tab-separated-values
Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcm92aWRlcl9pZCI6IjM4MTE1ZTA4LWVhOTUtMTFlYy1hYTVhLTViZGVjN2VmM2I0OCJ9.k6BIqItVjxjYVUT_EXnP-pHkzJu_6R0UXUye22rmHzs 

message
some message

###
GET http://localhost:3000/topic/tomatoes/limit/4
Content-Type: application/json
Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcm92aWRlcl9pZCI6IjM4MTE1ZTA4LWVhOTUtMTFlYy1hYTVhLTViZGVjN2VmM2I0OCJ9.k6BIqItVjxjYVUT_EXnP-pHkzJu_6R0UXUye22rmHzs 


###


GET http://localhost:3000/provider/1/from/204f3ebc-c7c0-4d78-a97b-0f3b582c3d84/limit/3
Content-Type: application/json
Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcm92aWRlcl9pZCI6IjM4MTE1ZTA4LWVhOTUtMTFlYy1hYTVhLTViZGVjN2VmM2I0OCJ9.k6BIqItVjxjYVUT_EXnP-pHkzJu_6R0UXUye22rmHzs 

